name: 🐞 Bug Report
description: File a bug/issue
title: "[Bug]: "
labels: ["bug"]
assignees:
  - rkkoranteng
body:
  - type: markdown
    attributes:
      value: This is embarrassing. I apprecaite your feedback!
  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: Tell me what went wrong.
      placeholder: Please give a detailed description of what you're experiencing.
    validations:
      required: true
